title: Your Blog Title
description: Notes, tutorials, and resources.
theme: minima

# When hosting as a Project Page (not username.github.io),
# set your site URL and baseurl for correct links.
url: https://cardspop.github.io
baseurl: /html

# Optional but nice: enables RSS and good meta tags
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Customize as you like later
minima:
  skin: auto
