title: CardsPop.io
description: Blue, red, and white — simple landing with a blog.
theme: minima

# Project Page under /cardspop
url: https://cardspop.github.io
baseurl: /cardspop

# Put posts under /blog/ path
permalink: /blog/:year/:month/:day/:title:output_ext

# Optional but nice: enables RSS and good meta tags
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Customize as you like later
minima:
  skin: auto

# Show About in the header nav
header_pages:
  - about.md
  - blog/index.md
  - guides/index.md
  - tools/index.md
  - sets/index.md
