title: Your Blog Title
description: Notes, tutorials, and resources.
theme: minima

# User/Org site at root domain
url: https://cardspop.github.io
# baseurl intentionally omitted for root site

# Optional but nice: enables RSS and good meta tags
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Customize as you like later
minima:
  skin: auto

# Show About in the header nav
header_pages:
  - about.md
